### ISSUE TITLE
Upgrading to hypre-2.16.0+

### ISSUE THREAD

**Issue by tzanio** [mfem/mfem#1276]
There are number of issues with the mfem use of hypre starting with hypre-2.16.0 that need to be addressed:

- [x] Fix [ex19p and ex21p](https://github.com/mfem/mfem/pull/1314#issuecomment-596923452)
- [x] Support for HYPRE_MIXEDINT, #933 -- addressed by #1583
- [x] Issues with SuperLU, #989, #983 
- [x] Segfault in parallel matrix addition, #1238
- [ ] Support for HYPRE_Init() and HYPRE_Finalize(), https://github.com/mfem/mfem/issues/1376#issuecomment-604795342

**Comment by tzanio** [comment]
The `HYPRE_MIXEDINT` support is being addressed in https://github.com/mfem/mfem/pull/1583

**Comment by tzanio** [comment]
`HYPRE_Init()` and `HYPRE_Finalize()` are also discussed in #1750

**Comment by tzanio** [comment]
Discussion continued in https://github.com/mfem/mfem/pull/2873
