### ISSUE TITLE
MFEM in xSDK

### ISSUE THREAD

**Issue by tzanio** [mfem/mfem#275]
Note: This is a mirror of https://github.com/xsdk-project/xsdk-issues/issues/11

MFEM is joining the xSDK-0.3 release, which requires that we conform to a set of [community policies](http://dx.doi.org/10.6084/m9.figshare.4495136). Our current policy gaps are:

- [x] **M1**: xSDK-specific options in CMake, xsdk-project/xsdk-issues#15 
- [x] **M3**: user-provided MPI communicators, xsdk-project/xsdk-issues#16 
- [x] **M8**: runtime API for version number, xsdk-project/xsdk-issues#37 
- [x] **M11**: disable output/redirect stdout, xsdk-project/xsdk-issues#18
- [x] **M16**: Spack support, xsdk-project/xsdk-issues#19

Discuss these policies, our compliance, and progress below.

**Comment by tzanio** [comment]
MFEM compatibility with xSDK policies:

https://github.com/xsdk-project/xsdk-policy-compatibility/blob/master/mfem-policy-compatibility.md

**Comment by tzanio** [comment]
Branch with xSDK-related changes:

**Comment by tzanio** [comment]
M1, M3, M8, M11 and M16 resolved by [mfem@xsdk-0.3.0-rc2](https://github.com/mfem/mfem/releases/tag/xsdk-0.3.0-rc2).
