### ISSUE TITLE
Roadmap for GPU support in mfem-4.0

### ISSUE THREAD

**Issue by tzanio** [mfem/mfem#813]
# Roadmap for the [mfem-4.0](https://github.com/mfem/mfem/milestone/3) release

### `mfem-4.0` - **Due: 5/22/19** - Pull request: ~#805~, ~#902~, #908, #756, #742, #878, #715, #911, #912, #913, #918, #921, #922 
- [x] **memory-dev** Try a `memory` type to isolate the memory manager from the `Device` class (#913)
- [x] Resolve #928 (static condensation not working in master)
- [x] Updated documentation and website for mfem-4.0 (https://github.com/mfem/web/pull/22)
- [x] **yohann/mesh_ext** PA API fixes: https://github.com/mfem/mfem/issues/813#issuecomment-490691572 and #904 
- [x] **mesh-ext-additions** Improve the integration of some of the new GPU classes with existing classes (#922)
- [x] **shared-kernels** Mass + diffusion shared memory kernels (#921)
- [x] ~**okina-nvidia** Bring shared memory capabilities into the PA kernels (#902)~
- [x] ~**okina-mmu** Different memory backends with support for Umpire, UVM and "debug" device (#805)~
- [x] ~~Linking cuda-enabled mfem with host linker~~
- [x] **inf-reciprocal** Address #915 (incorrect `./ex6p -pa -d cuda` with optimization) (#918)
- [x] **occa-omp** Enable OpenMP foralls with all OMP_MASK'ed devices (#912)
- [x] **stefanozampini/small-improvements** Various improvements and bugfixes in the PETSc support (#756)
- [x] **gzdata-collection-dev** gzstream support in DataCollection (#742)
- [x] **vfe-dev** Bugfix in `ExchangeFaceNbrData` for VectorFE (#878)
- [x] **najlkin:pr7** Bugfix in `Mesh::GetBdrElementTransformation()` (#715)
- [x] **compiler-warnings** Fix `nvcc` compiler warnings in `make all` (#908)
- [x] **ex22-rename** Rename Example 22 to Example 21 (#911)

### `mfem-4.0-rc2` - **Due: 4/24/19** - Pull requests: #862, #868, #870, #875, #882 
- [x] Add regression testing for GPU runs @ LLNL (#882 )
- [x] Fix `ex6`: avoid using `AtomicAdd` (#875)
- [x] Remove CUDA driver calls (#868)
- [x] Update `README` to mention GPU support (#870)
- [x] Update the code overview section in `CONTRIBUTING.md` to include GPU-related classes (#870)
- [x] Add CMake support for all new backend options (CUDA, OCCA, RAJA, OpenMP, etc.) (#862)

### `mfem-4.0-rc1` - Due: 4/11/19 - Pull request: #631 
- [x] Updates in the examples, class BilinearForm and related #851
- [x] mm erase fix
- [x] #849 Remove mm singleton + memory leaks
- [x] Add fallback kernels for (arbitrary) orders beyond 4 (~#758~, #850) 
- [x] ~**okina-macros** (#757) Templated kernel instantiations~
- [x] #845 Some tweaks to the mfem::Device class
- [x] #848 Reserve okina name for future kernel interface
- [x] Support `make cuda MFEM_USE_OPENMP=YES` (needs #780)
- [x] Test CUDA, RAJA, OCCA, etc. on more platforms (Linux, Mac, Lassen, Quartz, ...)
- [x] Document `MFEM_USE_CUDA`, `MFEM_USE_RAJA`, `MFEM_USE_OCCA` and `MFEM_USE_MM` in `INSTALL`
- [x] Application should not see/use internal included MFEM headers like `general/cuda.hpp`
- [x] Being able to compile external application depending on nvcc compiled MFEM without nvcc
- [x] Bring GPU kernels from occa-dev
- [x] Move and rename `dvector3.hpp` inside `vector.hpp`
- [x] **artv3/okina-raja** (#727) RAJA support (seq, omp, cuda)
- [x] **okina-tensors** (#754) Add small vector/array classes with `operator()`
- [x] **okina-ex6** (#777) Merge the GPU examples (1/1p, 6/6p) from `okina-examples`
- [x] **okina-bilininteg** (#775) Merge the integrators assembly level switch (FA, PA, EL & MF)
- [x] Perform `P` and `R` actions on the CPU
- [x] Move code from `dir/kernel/class.?pp` to `dir/class.?pp`
- [x] Clean up debug code and comments
- [x] Clean `config` class + rename
- [x] Fix styling to conform to current code
- [x] **okina-atomic** (#815) Support compute capability < 6.0
- [x] **artv3/okina-mode-switch** (#801) Add support for `GetAll`
- [x] **artv3/okina-regPointers** (#787) Add support for registering external pointers in the `mm`
- [x] **okina-fcoeff** (#820) Fix support for *host* function coefficient in PAMass

**Comment by acfisher** [comment]
Testing grid for ex1 as of:  8e1fa3141705d79a305a2871c37f800e5039e570

| dim | asm lvl |  device | o1 | o2 | o3 | o4 |
|:---:|:-------:|:-------:|:--:|:--:|:--:|:--:|
|  2  |    FA   | default |  S |  S |  S |  S |
|  2  |    FA   |   cuda  |  F |  F |  F |  F |
|  2  |    FA   | occacpu |  S |  S |  S |  S |
|  2  |    FA   | occacuda|  F |  F |  F |  F |
|  2  |    PA   | default |  S |  S |  S |  S |
|  2  |    PA   |   cuda  |  S |  S |  S |  S |
|  2  |    PA   | occacpu |  S |  S |  S |  S |
|  2  |    PA   | occacuda|  S |  S |  S |  S |
|  3  |    FA   | default |  S |  S |  S |    |
|  3  |    FA   |   cuda  |  F |  F |  F |  F |
|  3  |    FA   | occacpu |  S |  S |  S |    |
|  3  |    FA   | occacuda|  F |  F |  F |  F |
|  3  |    PA   | default |  S |  S |  S |  S |
|  3  |    PA   |   cuda  |  S |  S |  S |  S |
|  3  |    PA   | occacpu |  S |  S |  S |  S |
|  3  |    PA   | occacuda|  S |  S |  S |  S |

2D Mesh -  star.mesh
3D Mesh -  beam-hex.mesh
S - Success
F - Full assembly not supported in device mode

Looking good!

**Comment by dmed256** [comment]
@acfisher woah, pretty cool!

**Comment by v-dobrev** [comment]
Here are some things that I think we need to address:

* Class `GeometryExtension`:
  - objects of this class should be owned by the `Mesh` objects?
  - Members like `invJ`, `detJ`, `X`, should be computed only if used.
  - Do we need a store the `nodes`? This is the E-vector derived from the mesh nodes.
  - The role of `eMap` seems to overlap with the role of class `ElemRestriction`.

* Class `ElemRestriction`:
   - Rename to `ElementRestriction`.
   - `ElementRestriction` objects should be associated with a `FiniteElementSpace`.

* The global `static long sequence` in `bilininteg_ext.cpp` - this should not be global.

* The global `static GeometryExtension *geom` in `bilininteg_ext.cpp` - this should not be global.

* Class `DofToQuad`:
  - This class should store `B` and `G` for one `FiniteElement`.
  - Objects of this class should be owned by the respective `FiniteElement` objects.
  - Do not need the global container `AllDofQuadMaps`.
