### ISSUE TITLE
Development plan for mfem-4.1

### ISSUE THREAD

**Issue by camierjs** [mfem/mfem#931]
## From version 4.0
- [ ] Update the [building instructions](https://github.com/mfem/web/blob/master/src/building.md) with a section on "building with GPU support"
- [ ] Update Spack package (#970)
- [x] **hypre-errors-dev**: Flexible handling of hypre errors (#932)

## Improvements and bugfixes
- [ ] Improved documentation (#903)
- [ ] Support HYPRE_MIXEDINT (#933)

## Main features
- [x] Support for complex-valued linear systems (#584)
- [x] Prisms NC AMR support (#713)
- [x] TMOP improvements: #895, #799 
- [x] Interface to HiOp (#616)
- [x] gslib integration (#822) 

## GPU support
- [x] **rocm** ROCm/HIP support (#1009)
- [x] **raja-wrap**: Grid setup from RAJA Kernels (#1050) 
- [x] **dmpi** Bring MPI kernels from the engines branch (#1038)
- [x] **yohann/okina-gpu-libceed** libCEED support (#866 )
- [ ] **gmsshare**: Optimized 8th order 3D diffusion collocated kernels (#944) 
- [ ] **okina-jit** (#719) Bring the `MFEM_JIT` and `MFEM_TEMPLATE` instantiations capabilities
---
- [ ] Add kernels for simplices
- [ ] Add support for Acrotensor
- [ ] Add small vector GPU device functions
- [ ] Add support for GPU function coefficient
- [ ] Support for hypre preconditioners on the GPU
- [ ] Add support for element batching (currently ignored)
- [ ] Add some FA, EA or MF kernels (currently only PA kernels are implemented)

## Postponed
- [ ] 4D Meshes, Spaces and Solvers (#221)

## Done
- [x] ~Cleanup `DofToQuad` class~
- [x] ~Add `__share` and `inner` for loops capabilities~
- [x] ~Control device/host behavior at object, not global level?~
- [x] ~Store strides in tensor objects to improve performance?~
- [x] ~Aim to remove `Device::Enable` and `Device::Disable` from user code? (#896)~
- [x] ~**okina-mmcheck** (#741) Allow to use the `mmcheck` since startup and add pre-`main` support~
- [x] ~Clean-up `BilinearForm` -- use the major release as an opportunity to remove accumulated complexity (potentially breaking some API)~

**Comment by camierjs** [comment]
Closing in favour of the [review](https://github.com/orgs/mfem/teams/reviewers) process.
